- name: include variables
  hosts: all
  gather_facts: no
  tags: always
  tasks:
    - include_vars: dir='config/general' files_matching='.yml$'
    - include_vars: dir='config/board' files_matching='{{board}}.yml$'
    - include_vars: dir='config/postproc' files_matching='.yml$'

- name: router setup
  hosts: all

  roles:
    - { role: disable-deb-init-actions, tags: ['debinitactions'] }
    - { role: sshd-config, tags: ['sshdconfig'] }
    - { role: rootuser-setup, tags: ['rootuser'] }
    - { role: install-additional-packages, tags: ['packages'] }
    - { role: misc-configuration, tags: ['misc-config'] }
    - { role: disable-kernel-modules, tags: ['disable-modules'] }
    - { role: network-interfaces, tags: ['ifaces'] }
    - { role: accesspoint, tags: ['ap'] }
    - { role: monitoring, tags: ['monitoring'] }
    - { role: dns, tags: ['dns'] }
    - { role: firewall, tags: ['firewall'] }
    - { role: routing, tags: ['routing'] }
    - { role: adsl, tags: ['adsl'] }
    - { role: dyndns, tags: ['dyndns'] }
