- name: include override vars
  hosts: all
  gather_facts: no
  tags: always
  tasks:
    - include_vars: dir='vars_override' files_matching='.yml$'

- name: router setup
  hosts: all

  roles:
    - { role: disable-deb-init-actions, tags: ['debinitactions'] }
    - { role: sshd-config, tags: ['sshdconfig'] }
    - { role: rootuser-setup, tags: ['rootuser'] }
    - { role: wifi-firmwares, tags: ['firmwares'] }
    - { role: network-interfaces, tags: ['ifaces'] }
    - { role: accesspoint, tags: ['ap'] }
    - { role: monitoring, tags: ['monitoring'] }
    - { role: dns, tags: ['dns'] }
    - { role: firewall, tags: ['firewall'] }
    - { role: routing, tags: ['routing'] }
    - { role: adsl, tags: ['adsl'] }
    - { role: dyndns, tags: ['dyndns'] }
