- name: include override vars
  hosts: all
  gather_facts: no
  tags: always
  tasks:
    - include_vars: dir='vars_override' files_matching='.yml$'

- name: router setup
  hosts: all

  roles:
    - disable-deb-init-actions
    - disable-armbian-firstlogin
    - authorized_keys
    - { role: network-interfaces, tags: ['ifaces'] }
    - { role: accesspoint, tags: ['ap'] }
    - { role: dnsmasq, tags: ['dnsmasq'] }
