- name: router setup
  hosts: all

  roles:
    - disable-deb-init-actions
    - disable-armbian-firstlogin
    - authorized_keys
    - { role: network-interfaces, tags: ['ifaces'] }
    - { role: accesspoint, tags: ['ap'] }
