authorized_keys:
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVho9lnXabPkR2I+LSa91E6jGrFst25pt1NjUFDcO4u3fTBBLymleLREBx1n0ndVpkbilFICtKKwh5Zcl1ATVGc47643H48xy/QegwM+pjMcnS9xIQMp2uOK9h+qGfswEEox6LhBS6J0SRyH+4CiH9Z9faEcFtSXTWwvKfyXEeEunO8eprrvtsHzgUQ5kvELkvBDn1+b3lrhNDbyjjpgv0ol88Jx8I/fhezDctoGxfPjIcVNrN2vSJj57fKMSPJkwvrggVdiTNFS0c8tEyulLZ9AvPlRfLwKUljQ+AHrRoymKZp9jiCA2+7iPmI6rX3Bf1oqImXy077mH61kAwBXGf olaf@tackd'

