---

- name: uninstall unneeded networking packages
  package:
    name: "{{item}}"
    state: absent
  with_items:
    - network-manager
    - isc-dhcp-client
    - wpasupplicant
    - swconfig

- name: upload networking init script
  copy:
    src: files/networking
    dest: /etc/init.d/networking
    mode: 0755