---

- name: disable armbian 1st login activities
  file:
    path: /root/.not_logged_in_yet
    state: absent

- name: reset root password
  shell: echo "root:{{root_password}}" | chpasswd

- name: disable root password change requirement
  shell: chage -d -1 root

- name: add additional authorized_keys entries for root
  lineinfile:
    dest: ~/.ssh/authorized_keys
    line: "{{ item }}"
  with_items:
    - "{{ authorized_keys }}"
