# the board contains three interfaces -- eth0, eth1, eth2 -- where eth1 is a hardware switch
# with 6 ports lan1...lan6.
# We'll make eth0 the WAN interface, eth0 + the WiFi interface the LAN interface, and eth2 the
# management interface.

# Which interfaces to combine into which bridge interfaces (software switches),
# with which IPs.
# One of them must be the LAN interface, named {{lanif_name}}, IP {{lan_prefix}}.{{lan_host}}.
bridges:

  - name: "{{lanif_name}}"
    members:
    - "lan1"
    - "lan2"
    - "lan3"
    - "lan4"
    - "lan5"
    - "lan6"
    ip: "{{lan_prefix}}.{{lan_host}}"
    ipv6_mtu: 1400  # for IPv6 only (does this really work?)

  - name: "{{mgmtif_name}}"
    members:
    - "eth2"
    ip: "{{management_ip}}"


# WAN interface. The ADSL setup will configure this to be the PPPoE outgoing interface
wan_interface: eth0

# WLAN interface. Will be added to the {{lanif_name}} bridge interface
wlan_interface: wlan0
