# the board contains three interfaces -- eth0, eth1, eth2 -- where eth0 is the port on the far left
# (labeled "WAN" on the standard enclosure), eth1 is a hardware switch with 6 ports lan1...lan6
# (labeled "LAN" on the standard enclosure), and eth2 is the SFP port (labeled "SFP" on the standard
# enclosure).
# We expect a USB WiFi stick that's supported by the kernel to be plugged into the box, showing
# up as wlan0.
# We'll make eth0 the WAN interface, eth1's ports + the WiFi interface
# the LAN interface, and eth2 the management interface (which an SFP
# port is total overkill for, but anyway).

bridges:

  - name: "{{lanif_name}}"
    members:
    - "lan1"
    - "lan2"
    - "lan3"
    - "lan4"
    - "lan5"
    - "lan6"
    ip: "{{lan_prefix}}.{{lan_host}}"
    ipv6_mtu: 1400  # for IPv6 only (does this really work?)

  - name: "{{mgmtif_name}}"
    members:
    - "eth2"
    ip: "{{management_ip}}"

other_interfaces:
  - eth1
