- name: install dnsmasq package
  package:
    name: "{{item}}"
    state: present
  with_items:
    - resolvconf
    - dnsmasq

- name: roll out dnsmasq config
  template:
    src: templates/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq service

- name: enable and start dnsmasq service
  systemd:
    name: dnsmasq.service
    enabled: True
    state: started
    daemon_reload: True
    detect_early_failure: yes
  notify: restart dnsmasq service
