- name: set sshd options
  template:
    src: templates/routerbox.conf.j2
    dest: /etc/ssh/sshd_config.d/routerbox.conf
    mode: 0644
  notify:
    - restart sshd service

- name: configure ssh host keys
  include_tasks: write_hostkey.yml
  with_dict: "{{sshd_host_private_keys}}"
  no_log: True
